export const projectsData = [
  {
    name: "HRIS",
    icon: "👥",
    iconBg: "rgba(0,229,255,0.1)",
    accentColor: "#00e5ff",
    category: "Web App",
    description:
      "A comprehensive Human Resource Information System built to digitize and automate core HR operations across an organization.",
    features: [
      "Real-time employee attendance tracking with biometric integration",
      "Automated payroll processing with tax and deduction computation",
      "Overtime management with approval workflows",
      "HR reporting dashboard with exportable reports",
    ],
    tech: ["ASP.NET /.NET Core MVC","API", "C#", "MSSQL", "Crystal Reports", "Bootstrap","JavaScript"],
  },
  {
    name: "Hospital Billing System",
    icon: "🏥",
    iconBg: "rgba(255,107,107,0.1)",
    accentColor: "#ff6b6b",
    category: "Web App",
    description:
      "A billing module that automates the generation of Statement of Accounts (SOA) for patients, consolidating all charges from admission to discharge.",
    features: [
      "Auto-generate SOA for medicines, procedures, and room charges",
      "PhilHealth deduction and HMO computation integration",
      "Discount management (senior, PWD, employee)",
      "Itemized billing with print-ready PDF export",
    ],
    tech: ["ASP.NET /.NET Core MVC","API", "C#", "MSSQL", "SAP Crystal Reports", "jQuery","JavaScript"],
  },
  {
    name: "Online Payment System",
    icon: "💳",
    iconBg: "rgba(123,97,255,0.1)",
    accentColor: "#7b61ff",
    category: "Fintech",
    description:
      "A centralized payment repository that consolidates and tracks payments across all connected internal systems in real time.",
    features: [
      "Unified payment ledger across multiple systems",
      "Real-time transaction monitoring and reconciliation",
      "Multi-payment method support (cash, card, e-wallet)",
      "Audit trail and payment history reports",
    ],
    tech: [".NET Core","C#", "MSSQL", "REST API", "Bootstrap","JavaScript","AngularJS"],
  },
  {
    name: "eSerbisyo – ETitle",
    icon: "🏛️",
    iconBg: "rgba(6,214,160,0.1)",
    accentColor: "#06d6a0",
    category: "Gov Web App",
    description:
      "A government-facing online web application that allows citizens to request land title information, track status, and receive digital delivery — eliminating the need for in-person visits.",
    features: [
      "Online land title request submission portal",
      "Real-time status tracking per request",
      "Digital delivery and notification system",
      "Secure citizen authentication and document validation",
    ],
  tech: [".NET Core MVC","API" ,"C#", "MSSQL", "REST API", "Bootstrap","JavaScript","AngularJS"],
  },
  {
    name: "DENR Linkage API",
    icon: "🔗",
    iconBg: "rgba(255,209,102,0.1)",
    accentColor: "#ffd166",
    category: "API",
    description:
      "A secure RESTful API enabling seamless and standardized data exchange between LARES and the Department of Environment and Natural Resources (DENR).",
    features: [
      "Secure inter-agency data exchange endpoints",
      "Standardized data format and schema validation",
      "Error handling and retry mechanisms",
      "API key authentication and rate limiting",
    ],
    tech: [".NET Core API", "C#", "REST API", "MSSQL"],
  },
  {
    name: "Unified Payment System",
    icon: "🏦",
    iconBg: "rgba(247,37,133,0.1)",
    accentColor: "#f72585",
    category: "Fintech",
    description:
      "A multi-channel online payment gateway that allows clients to pay obligations through e-wallets, online banking, and card payments from a single unified interface.",
    features: [
      "GCash and Maya e-wallet integration",
      "Landbank, DBP, and major bank online payment support",
      "Credit and debit card processing (Visa/Mastercard)",
      "Payment confirmation, receipt generation, and reconciliation",
    ],
    tech: ["ASP.NET Core", "C#", "Payment Gateway API", "MSSQL", "PostgreSQL","Angular"],
  },
  {
    name: "API Development & AI Integration",
    icon: "⚙️",
    iconBg: "rgba(0,229,255,0.08)",
    accentColor: "#00e5ff",
    category: "API",
    description:
      "Enterprise-grade backend API development using .NET Core, with integrations to third-party services and AI Large Language Models for intelligent automation.",
    features: [
      "RESTful API design with Swagger/OpenAPI documentation",
      "Third-party service integrations (SMS, email, payment gateways)",
      "AI LLM integration (OpenAI, Claude, Gemini) for smart features",
      "Secure authentication with JWT and OAuth2",
    ],
    tech: [".NET Core API", "C#", "OpenAI", "JWT", "REST API", "MSSQL"],
  },
  {
    name: "Admin Dashboard",
    icon: "📊",
    iconBg: "rgba(123,97,255,0.1)",
    accentColor: "#7b61ff",
    category: "Web App",
    description:
      "A powerful management dashboard for monitoring business performance — tracking sales, income, expenses, and operational reports with visual analytics.",
    features: [
      "Real-time sales and revenue charts",
      "Income vs. expense tracking with trend analysis",
      "Exportable management reports (PDF, Excel)",
      "Role-based access for admin and staff views",
    ],
    tech: [".NET Core", "C#", "MSSQL", "Laravel", "Bootstrap"],
  },
  {
    name: "Inventory Generator (Native)",
    icon: "📦",
    iconBg: "rgba(6,214,160,0.1)",
    accentColor: "#06d6a0",
    category: "Mobile App",
    description:
      "A native mobile application for inventory management featuring barcode scanning, POS functionality, and receipt generation — built for retail and warehouse operations.",
    features: [
      "Barcode/QR code scanning for product lookup",
      "Point-of-sale (POS) cashier mode",
      "Thermal receipt generation and printing",
      "Stock level tracking and low inventory alerts",
    ],
    tech: ["React Native", "TypeScript", "Expo", "REST API", "SQLite"],
  },
  {
    name: "AXA Insurance Web & Mobile",
    icon: "🛡️",
    iconBg: "rgba(255,107,107,0.1)",
    accentColor: "#ff6b6b",
    category: "Mobile App",
    description:
      "A paperless insurance sales platform for AXA agents, enabling digital product selling, automated computation of premiums, and comprehensive reporting — available on web and mobile.",
    features: [
      "Digital product catalog and paperless policy issuance",
      "Automated premium and benefit computation engine",
      "Agent performance and sales reports",
      "Client management and policy tracking dashboard",
    ],
  tech: ["ASP.NET/.Net Core MVC", "C#", "REST API", "MSSQL",,"SQLite", "Xamarin/MAUI"],
  },
  {
    name: "UMi Core API",
    icon: "🧩",
    iconBg: "rgba(255,209,102,0.1)",
    accentColor: "#ffd166",
    category: "API",
    description:
      "A modular API backbone that serves as the unified core for all client systems — enabling legacy application migration into scalable, maintainable microservice-based architectures.",
    features: [
      "Centralized API gateway for all client systems",
      "Legacy system migration to modular REST APIs",
      "Cross-system authentication and session management",
      "Versioned API support for backward compatibility",
    ],
    tech: [".NET Core API", "C#", "REST API", "MSSQL"],
  },
];

export const resumeData = {
  name: "James Griño Cedeño",
  age: "27 years old (May 5,1998)",
  title: "Full-Stack .Net Developer",
  tagline: "Building robust systems, APIs & mobile apps for 6+ years.",
  summary:
    "Resourceful and highly organized professional with 6+ years of experience, strong leadership, and team-building abilities. Committed to excelling in my field while fostering a positive and collaborative work environment. Known for being adaptable, dependable, and driven by a strong work ethic.",
  contact: {
    email: "cedenojames58@gmail.com",
    phone: "+639164048301",
    location: "Koronadal City, South Cotabato, Philippines (Open for relocation)",
  },
  experience: [
    {
      company: "BOLDR PH",
      role: "Back-End Engineer",
      location: "Pasig City",
      period: "January 2026 – April 2026",
      highlights: [
        "Designed, developed, and maintained server-side applications and APIs.",
        "Built and optimized business logic, database interactions, and application workflows for seamless efficiency.",
        "Collaborated with cross-functional teams to deliver scalable, secure, and high-performance solutions.",
        "Key tasks: API development and integration with third-party services.",
      ],
    },
    {
      company: "Ascendion (AXA Philippines)",
      role: ".NET Developer",
      location: "Makati City",
      period: "October 2023 – May 2025",
      highlights: [
        "Developed and maintained software applications to streamline insurance operations.",
        "Troubleshot and resolved complex technical issues ensuring continuous system availability.",
        "Engaged in the complete software development lifecycle to meet business objectives.",
      ],
    },
    {
      company: "SpaceTech Services",
      role: "Freelance API Developer",
      location: "Koronadal City",
      period: "January 2023 – October 2023",
      highlights: [
        "Developed and enhanced an API handling all data for the admin web portal and mobile applications.",
        "Enhanced the portal to allow users to monitor gross and net transactions and generate reports.",
        "Contributed to the development of native mobile applications.",
      ],
    },
    {
      company: "Land Registration Systems (LARES)",
      role: "Systems Engineer",
      location: "Quezon City",
      period: "July 2021 – January 2023",
      highlights: [
        "Enhanced the eSerbisyo Portal/API to facilitate online Title Detail requests with real-time status updates.",
        "Developed a Unified Payment Integration Portal for seamless transaction processing.",
        "Developed the DENR Linkage API to support efficient data exchange between parties.",
      ],
    },
    {
      company: "Geodata Solution Inc.",
      role: "Programmer",
      location: "Koronadal City",
      period: "May 2019 – July 2021",
      highlights: [
        "Collaborated in enhancing an HRIS, optimizing attendance tracking, payroll processing, and HR reporting.",
        "Engineered an automated hospital billing system producing precise Statements of Account.",
        "Led the development of an online payment portal integrating GCash, Maya, and credit/debit cards.",
      ],
    },
  ],
  education: {
    school: "ACLC College of Marbel",
    degree: "Bachelor of Science in Information Technology",
    location: "Koronadal City",
    period: "June 2015 – April 2019",
  },
  skills: [
    { name: "C#", years: 6, category: "Backend" },
    { name: "ASP.NET & .NET Core MVC", years: 6, category: "Backend" },
    { name: ".NET Core API (Swagger)", years: 6, category: "Backend" },
    { name: "Microsoft SQL Server", years: 6, category: "Database" },
    { name: "HTML / CSS / Bootstrap", years: 3, category: "Frontend" },
    { name: "JavaScript / jQuery / AngularJS", years: 3, category: "Frontend" },
    { name: "GIT & TFS", years: 3, category: "DevOps" },
    { name: "Azure (CI/CD)", years: 2, category: "DevOps" },
    { name: "PostgreSQL / Sybase", years: 1, category: "Database" },
    { name: "Xamarin", years: 1, category: "Mobile" },
    { name: "React Native / TypeScript / Expo", years: 0, category: "Mobile" },
    { name: "Laravel (PHP)", years: 0, category: "Backend" },
    { name: ".NET MAUI", years: 0, category: "Mobile" },
    { name: "AWS (EC2, RDS, KMS)", years: 0, category: "DevOps" },
    { name: "SAP Crystal Report", years: 0, category: "Tools" },
    { name: "API Integration (Payment Gateway, SMS)", years: 0, category: "Tools" },
    { name: "IIS Deployment", years: 0, category: "DevOps" },
    { name: "SDLC & Scrum", years: 0, category: "Methodology" },
    { name: "AI Tools (OpenAI, Copilot, Claude, Gemini)", years: 0, category: "Tools" },
    { name: "VS Code, Visual Studio (version 16,22,26), Android Studio", years: 0, category: "Tools" },
  ],
  references: [
    { company: "Geodata Solution Inc.", name: "Mrs. Grishiele Dida", contact: "09367969747" },
    { company: "LARES", name: "Ms. Kathlyn Labaguis", contact: "09274114224" },
    { company: "SpaceTech Services", name: "Ms. Mai Bulbeque", contact: "09467005966" },
    { company: "AXA Philippines", name: "Relox Raymond", contact: "09985585289" },
    { company: "BOLDR PH", name: "Engelbert Canceran", contact: "09772611608" },
  ],
};
